--NON-REPEATABLE READ EXAMPLE - REPEATABLE READ - UPDATE

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;  
GO  
BEGIN TRANSACTION updateTran;  
GO  

update Production.Product
set ListPrice = 123
where ProductID = 749


COMMIT TRANSACTION updateTran

